[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Vu Quang Phuc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
_solver = { path = "src/_solver" }