[package]
name = "_solver"
version = "0.1.0"
authors = ["Vu Quang Phuc <phuc.vu-quang@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
_computer = { path = "../_computer" }